mattermost/mattermost-operator

deploy/crds/mattermost_v1alpha1_clusterinstallation_crd.yaml, pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go, pkg/controller/clusterinstallation/controller.go, pkg/controller/clusterinstallation/mattermost.go, pkg/controller/clusterinstallation/secrets.go
After the implementation https://mattermost.atlassian.net/browse/MM-14982, I think a bit more and looked other operators.
and when you need to set some external information the user is responsible to create the configmap or the secret.
In our case make sense to have a secret instead of setting the DNS (which contains passwords/user) directly in the manifest.
=> refactor external database to use an existing secret

Gopkg.lock, cmd/manager/main.go, pkg/log/log.go, pkg/log/log_test.go, test/e2e.sh
This change wraps the logrus logger in a `logr.Logger` interface
so that it can be used by the mattermost operator packages. The
deferred logging in these packages requires this type of interface.
https://mattermost.atlassian.net/browse/MM-15110
https://mattermost.atlassian.net/browse/MM-15111
=> [MM-15110 | MM-15111] Migrate operator from zap to logrus logging

deploy/crds/mattermost_v1alpha1_clusterinstallation_crd.yaml, pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go, pkg/controller/clusterinstallation/controller.go, pkg/controller/clusterinstallation/mattermost.go, pkg/controller/clusterinstallation/utils.go
This change introduces the following:
- Full 'reconciling' and 'stable' state support
- Final health and validity checks for the mattermost installation
k8s objects
- Initial upgrade support for mattermost versions
- Support for updating deployment replica count
- Minor logging bug fixes
Initial support for https://mattermost.atlassian.net/browse/MM-15372
Other Notes:
This should be considered initial mattermost upgrade support. While the swapping out of images works, I sporadically ran into issues with DB connectivity that should be looked into further.
Regardless, the improved state support in this PR will start to give us confidence that our installations are actually running correctly instead of just creating the k8s objects and crossing our fingers.
=> [MM-15372] Enhanced state and upgrade support

pkg/controller/clusterinstallation/utils.go
when scaling up or down or any other updates the error message that was using is not 100% correct because depends on the state and the `terminating ` is not correct.
Example, when scaling up it creates a new pod but the error shows terminating which is not true.
logs when the change is applied:
```
time="2019-05-17T08:42:18Z" level=error msg="[opr.kubebuilder.controller] mattermost pod \"test-579cc784d5-9htf4\" is \"Pending\"" controller=clusterinstallation err.ctx="Reconciler error" request=default/test
time="2019-05-17T08:42:23Z" level=info msg="[opr.clusterinstallation.controller] Reconciling ClusterInstallation" Request.Name=test Request.Namespace=default
```
this is a smal change to make more clear the message.
=> fixing the error message to the correct phase

deploy/crds/mattermost_v1alpha1_clusterinstallation_crd.yaml, pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go, pkg/apis/mattermost/v1alpha1/zz_generated.deepcopy.go, pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go, pkg/controller/clusterinstallation/controller.go, pkg/controller/clusterinstallation/controller_test.go, pkg/controller/clusterinstallation/mattermost.go, pkg/controller/clusterinstallation/utils.go
We can use Ingress (then need to install an ingress controller) or now we can use a service type Loadbalancer, it will create a loadbalancer and assign the MM pods to receive the traffic.
Also added this information in the get the installation
for example, if you have a ingress it will return the DNS name like
```bash
$ kubectl get clusterinstallation test
NAME   STATE    IMAGE                                      VERSION   ENDPOINT
test   stable   mattermost/mattermost-enterprise-edition   5.11.0    demo.cpanato.spinmint.com
```
if using the loadbalancer will return the hostname for the ELB in AWS or the IP in the case of Azure
```bash
$ kubectl get clusterinstallation test
NAME   STATE    IMAGE                                      VERSION   ENDPOINT
test   stable …
```
=> add service type loadbalancer

Makefile, deploy/operator.yaml, docs/mattermost-operator/mattermost-operator.yaml
I know I said I was going to get rid of the yaml file under docs but it makes it much nicer to have a single yaml to run instead of 4-5 so instead I made it easy to generate that file going forward. Open to other solutions/suggestions.
=> Add makefile target to generate operator install YAML

pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
This probe checks that the `/api/v4/system/ping` endpoint is alive
and responding.
Fixes https://mattermost.atlassian.net/browse/MM-16031
Note: in the future we probably want to add header checks which will allow us to also confirm that arbitrary values are correct: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request
=> [MM-16031] Add liveness probe to mattermost deployment

deploy/crds/mattermost_v1alpha1_clusterinstallation_crd.yaml, deploy/operator.yaml, pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go, pkg/controller/clusterinstallation/controller.go, pkg/controller/clusterinstallation/controller_test.go, pkg/controller/clusterinstallation/utils.go
This change allows the operator to report status of cluster
installations more often during reconciliation. Also, the status
reported now includes a new value for the number of updated
replicas that are running. This can be compared against the total
number of pods targeted by the operator.
https://mattermost.atlassian.net/browse/MM-15595
=> [MM-15595] Enhance status reporting

deploy/operator.yaml, deploy/role.yaml, docs/mattermost-operator/mattermost-operator.yaml, pkg/controller/clusterinstallation/mattermost.go, pkg/controller/clusterinstallation/mattermost_test.go, pkg/log/log.go
This change includes improvements to the ability of the operator
to move between mattermost versions. The operator will now run
a job of the requested image version in order to perform any
database migrations that may be required. If those complete
successfully then the deployment will be updated to use the new
mattermost image as well.
This change also improves logging and corrects an issue with `e2e`
tests not running the correct operator image.
Fixes https://mattermost.atlassian.net/browse/MM-15977
=> [MM-15977] Enhance mattermost version change behavior

pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
We weren't enabling HA for licensed deployments.
=> Correctly set cluster settings for licensed MM deployments

pkg/apis/mattermost/v1alpha1/clusterinstallation_sizes.go
This change adds two new installation sizes that are tuned for
use when testing and developing.
https://mattermost.atlassian.net/browse/MM-17499
=> [MM-17499] Add new development-focused installation sizes

.circleci/config.yml
coverall is down since yestarday or more and the pipeline is failing.
This change not fail the pipeline if we cannot push the results to coveralls
pr from cloud: https://github.com/mattermost/mattermost-cloud/pull/67
```
#!/bin/bash -eo pipefail
goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_REPO_TOKEN
Bad response status from coveralls: 405
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
```
=> not fail the pipeline if coveralls is down

docs/mysql-operator/mysql-operator.yaml, pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go, test/e2e.sh, test/e2e/mattermost_test.go
update the mysql operator to version 0.3.2
- in this new version they changed the deployment to stateful sets
@gabrieljackson i dont know how we will handle this update in running cluster in the cloud. Does the provisioner delete all the things in the namespace and re install everything from scratch?
=> udpate mysql operator to 0.3.2

pkg/controller/clusterinstallation/bluegreen.go, pkg/controller/clusterinstallation/mattermost.go
When creating a cluster installation and using the service as a load balancer `UseServiceLoadBalancer = true`  we dont need to create and check the ingress because this resource is not used at all
=> dont create ingress when using the service as loadbalancer

pkg/controller/clusterinstallation/mattermost.go, pkg/controller/clusterinstallation/mattermost_test.go, test/e2e/mattermost_test.go
Hi everyone, this change should resolve [MM-16276](https://mattermost.atlassian.net/browse/MM-16276).
After this change, when `updateMattermostDeployment` detects that an update `Job` needs to be run, it does not wait for the `Job` to complete before returning control back to the reconciliation loop. Instead, it starts the `Job` and then returns an error each time it is called until the update succeeds. This keeps the cluster `Reconciling` until the update completes.
When the update `Job` is complete, `updateMattermostDeployment` will detect this and clean up the created `Job` and `Pod`, regardless as to whether it succeeded or failed.
This change in architecture allows update to overcome the limitation previously imposed by the 1 minute timeout.
=> MM-16276 Allow k8s reconcile loop to monitor ongoing updates

pkg/controller/mattermostrestoredb/mattermostrestoredb_controller.go
when not adding the namespace for filter out other pods show up in the results set and mess up the controller.
=> fix missing namespace to filter out the pods

pkg/controller/clusterinstallation/controller_test.go, pkg/controller/clusterinstallation/utils.go
The final health check for the Mattermost pods didn't check for
readiness. This could lead to the cluster installation passing
the operator check and being marked as stable, only to fail future
deployment health checks and then be restarted.
https://mattermost.atlassian.net/browse/MM-19298
=> Check Mattermost pod readiness

pkg/controller/clusterinstallation/utils.go
The error returned would originally have been wrapping a `nil` value.
=> Fix error returned by checksecret

pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
With this we can start tracking metrics specific to MM in Prometheus/Grafana. Tested with Prometheus on my dev EKS cluster.
=> Enable metrics for MM server

.circleci/config.yml
Before, this test would only check generated code. It now ensures
the manifests were generated properly as well.
https://mattermost.atlassian.net/browse/MM-20176
=> Ensure generate-test checks generated manifests

docs/examples/full.yaml, pkg/apis/mattermost/v1alpha1/clusterinstallation_test.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go, pkg/controller/clusterinstallation/controller_test.go, pkg/controller/clusterinstallation/mattermost_test.go, test/constants.go, test/e2e/mattermost_test.go
This also moves most of the manually-defined Mattermost version
strings we set for tests to two constants. This should reduce the
chance for error in the future.
=> Upgrade default Mattermost version to 5.19.1

deploy/crds/mattermost.com_clusterinstallations_crd.yaml, pkg/apis/mattermost/v1alpha1/clusterinstallation_test.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go, pkg/apis/mattermost/v1alpha1/zz_generated.deepcopy.go, pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go
This change adds the ability to specify new env vars for Mattermost
application pods in the ClusterInstallation spec. These env vars
will replace existing variables with the same name or will be
appended if they are new.
Partial fix for:
https://mattermost.atlassian.net/browse/MM-21845
https://mattermost.atlassian.net/browse/MM-21846
=> Add arbitrary Mattermost pod environment variables

version/version.go
This is updated to report a correct version when logged by the
operator.
=> Set operator version number variable

Makefile, README.md
Since moving to Go Modules, the Dep tooling and processes are no
longer needed.
https://github.com/mattermost/mattermost-operator/issues/129
=> Remove old Go Dep instructions and update Makefile

deploy/crds/mattermost.com_clusterinstallations_crd.yaml, pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go, pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go, pkg/controller/clusterinstallation/mattermost.go, pkg/controller/clusterinstallation/mattermost_test.go
This PR adds support to create TLS when creating the Ingress resource.
When user want to create the ingress and TLS support need to set the `UseIngressTLS` and the ingress annotations (for example for cert-manager) to make it work
- Fixes: https://github.com/mattermost/mattermost-operator/issues/97
And it is related to https://github.com/mattermost/mattermost-operator/pull/113 but due inactivity we decided to move forward
JIRA: https://mattermost.atlassian.net/browse/MM-23256
=> [MM-23256] TLS support for ingress resource

deploy/crds/mattermost.com_clusterinstallations_crd.yaml, pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go, pkg/apis/mattermost/v1alpha1/zz_generated.deepcopy.go, pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go, pkg/controller/clusterinstallation/controller_test.go, pkg/controller/clusterinstallation/utils.go
This PR adds support for custom Resource labels.
At the moment the Mattermost operator is applying some default labels in all resources. With this change a user can add the resourceLabels section in the cluster installation and specify a map of labels that will be applied in all resources. 
This change covers blue/green deployments too.
A new function called ClusterInstallationSelectorLabels was created to cover selector labels. The reason is that selector labels are immutable and cannot be edited after creation.
=> Mm 23681 - Adding support for custom resource labels

.github/workflows/notify-release.yml
With this GH Action every time we create a new release this action will be triggered and will post the release notification in the mattermost channel, in this case in the `Developers: Operators` channel, the webhook is already configured in the repo.
n/a
```release-note
NONE
```
=> add job to notify releases into a Mattermost channel

pkg/controller/clusterinstallation/minio.go
Allows the operator to work with clusters that don't use the default "cluster.local" domain name.  SQL's reference uses {service name}.{namespace} without the `svc.cluster.local` for its connection string. 
This change applies that same DNS approach to the minio service. 
Fixes https://github.com/mattermost/mattermost-operator/issues/143
```release-note
Fixes bug in minio connection when not using default "cluster.local" cluster domain. 
```
=> Remove hard-coded cluster DNS for minio

.circleci/config.yml, test/kind-config.yaml
- update kind to release 0.8.1
- update kubernetes to 1.16.9
Since we are planning to move to mattermost-cloud to use kops 1.16 lets start testing the operator with the same release of k8s
N/A
```release-note
Update Kind to release 0.8.1 and start testing with K8s 1.16.9 clusters
```
=> Update e2e kind cluster to user kind 0.8.1 and Kubernetes 1.16.9

pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
This changes the default version of Mattermost that is deployed
from 5.19.1 to 5.23.1.
```release-note
Bump default Mattermost version to 5.23.1
```
=> Bump default Mattermost version

pkg/apis/mattermost/v1alpha1/clusterinstallation_sizes.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_test.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
This change adds negative replica handling for the Mattermost app
deployment. Setting a negative number originally led to an invalid
deployment specification. Now, negative numbers will be converted
into 0, resulting in a valid deployment with 0 Mattermost app
containers.
Note that this is different from setting 0 in the ClusterInstallation
spec as that is the default value which will be updated to whatever
the size value specifies. This should probably be refactored in the
future.
Note: I know it's a bit odd that setting `0` for replicas will use the
default value size and setting `< 0` will translate to `0`, but this
seems like a good temporary way to prevent the bug and allow
for testing app deployments with no replicas. Once we start
handling size updates better we can look into a …
=> Handle negative Mattermost replicas

pkg/controller/clusterinstallation/utils.go
This updates the final reconciliation check to match the negative
replica setting logic for the Mattermost app deployment.
Relates to https://github.com/mattermost/mattermost-operator/pull/151
Fixes https://mattermost.atlassian.net/browse/MM-26024
```release-note
Handle negative replica count on final check
```
=> Handle negative replica count on final check

.circleci/config.yml, Makefile, build/Dockerfile, test/kind-config.yaml
- bump go image to 1.14.4
- bump alpine image to 3.12
- set the test k8s cluster to be 1.17
```release-note
- bump go image to 1.14.4
- bump alpine image to 3.12
- set the test k8s cluster to be 1.17
```
=> Update tests to use k8s 1.17

pkg/controller/clusterinstallation/mattermost.go
Removing the probes from the Job (update mattermost checker) because this is a short live execution and we don't need to have the readiness probe to start receiving traffic because this will not serve any request.
Also, the liveness can kill the job before it completes its execution, which is the case in community-daily (more context [see this 🧵 ](https://community-daily.mattermost.com/core/pl/1it9rb319pgs3x33j4wsyh4f3h) 
The job will run a specific command and will exit with success or fail which is we will check later. If the image does not exist it will fail in the initialization part and we don't need the probes for that.
n/a
```release-note
job: remove probes from the job image checker
```
=> update checker: remove probes from the job

Makefile, deploy/crds/mattermost.com_clusterinstallations_crd.yaml, pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go, pkg/apis/mattermost/v1alpha1/zz_generated.deepcopy.go, pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go, pkg/mattermost/helpers.go, pkg/mattermost/helpers_test.go, pkg/mattermost/mattermost.go
Sometimes, we need to deal the MM require an additional startup time on their first initialization. 
In such cases, it can be tricky to set up liveness probe parameters without compromising the fast response to deadlocks that motivated such a probe. 
The trick is to set up a startup probe with the same command, HTTP or TCP check, with a failureThreshold * periodSeconds long enough to cover the worse case startup time.
So after some knowledge refresh I discovery the new probe called `startupProbe` that works only in the initialization part, and after that the `livenessProbe` assume.
N/a
```release-note
probes: add startup probe to take care for the starting up process
```
/cc @jwilander
=> probes: add startup probe to take care for the starting up process

pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
Staying up to date.
```release-note
None
```
=> Bump default Mattermost version to 5.25.0

pkg/apis/mattermost/v1alpha1/clusterinstallation_test.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
Add the option to use digest instead of tags.
Some users use digest instead of tags because that digests are immutable and tags are mutable.
In our cloud use case:
We pull the master tag daily to update community-daily and the process of that is:
- pull the master tag
- retag master adding a suffix, ie ci_build env var
- push the newly tagged image which is the same as the current master
- update the manifest to use the new image
using the digest we avoid the tagging and pushing a duplicate image
n/a
```release-note
add option to use digest id instead of tag
```
=> add option to use digest id instead of tag

version/version.go
bump version to prepare the 1.6.0 release
```release-note
NONE
```
=> bump version to prepare the 1.6.0 release before the v1beta1

.circleci/config.yml, .gitignore, Makefile
Similar we have done for mattermost-cloud this adds a make entry to check outdated modules.
The job in the pipeline is a non-blocking
will output something like
```
+--------------------------------------------+------------------------------------+------------------------------------+--------+------------------+
|                   MODULE                   |              VERSION               |            NEW VERSION             | DIRECT | VALID TIMESTAMPS |
+--------------------------------------------+------------------------------------+------------------------------------+--------+------------------+
| github.com/banzaicloud/k8s-objectmatcher   | v1.3.3                             | v1.4.0                             | true   | true             |
| github.com/go-logr/logr …
```
=> add check modules to check outdated dependencies

README.md, deploy/crds/mattermost.com_clusterinstallations_crd.yaml, docs/examples/full.yaml, pkg/apis/mattermost/v1alpha1/clusterinstallation_sizes.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_test.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go, pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go, pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go, pkg/controller/clusterinstallation/controller_test.go
Modify `spec.Size` field of `ClusterInstallation` CR to be treated as write-only.
This prevents from inconsistency between Replicas and Resources values, and Size value. This also allows to modify installation size after `ClusterInstallation` CR has been created.
Fixes https://github.com/mattermost/mattermost-operator/issues/123
```release-note
NONE
```
=> [GH-123] Treat Size as an write-only field

pkg/controller/clusterinstallation/create_resources.go, pkg/mattermost/helpers.go, pkg/mattermost/helpers_test.go, pkg/mattermost/mattermost.go
Removing the startup probe because it is not available by default in the 1.17 k8s clusters and this was causing the infinite loop in the reconciliation hammering the API 
n/a
```release-note
probes: remove startup probe because 1.17 this is not enabled and was causing reconcile infinite loop
```
=> probes: remove startup probe because 1.17 this is not enabled and was causing reconcile infinite loop

pkg/apis/mattermost/v1alpha1/clusterinstallation_sizes.go
Update the CPU and memory requests and limits for the services that we deploy.
Some requests were set to a huge value and maybe we don't need that, since the request is the minimum needed to the service start running and looking at our community server the CPU was not requesting too much.
In one type of installation (5000 users ), it was requesting 3.5 CPU this is to a huge consumption CPU app, out services is not that hungry for CPU, and with that in a "normal" cluster will be never scheduled and most likely will run alone in one node, and will need more nodes to host the side apps (db/minio) because those were requesting a lot of CPU as well.
This PR reduces the requests for bot CPU/memory and try to standardize those.
If we merge that we might want to merge in the `release-1.6` branch …
=> resources: update cpu/mem requests and limits

pkg/mattermost/mattermost.go
This simplifies the logic for enabling Mattermost server clustering
by always setting the default values. They will be ignored when no
license is present.
Fixes https://mattermost.atlassian.net/browse/MM-26907
```release-note
Always set clustering config
```
=> Always set clustering config

go.mod, go.sum, pkg/controller/clusterinstallation/controller.go, pkg/controller/clusterinstallation/create_resources.go, pkg/controller/clusterinstallation/mattermost.go, pkg/controller/clusterinstallation/minio.go, pkg/controller/clusterinstallation/utils.go, pkg/mattermost/helpers.go, pkg/mattermost/helpers_test.go, pkg/mattermost/mattermost.go, vendor/github.com/banzaicloud/k8s-objectmatcher/patch/annotation.go, vendor/github.com/pborman/uuid/time.go, vendor/github.com/pborman/uuid/version4.go, vendor/modules.txt
This change refactors all controller logic related to updating the
state field of a ClusterInstallation's status. This was done to
correct an issue where the state value could be temporarily
incorrect. As part of this refactor, the following changes were
also made:
- Improved logging of status changes as well as other important
events. More logging fields added as well.
- Improved error handling by returning wrapped errors and letting
the caller log as necessary.
- Removed false logs that showed up when not using the mysql or
minio operators.
- Cherry-pick a change to remove the startup probe being set in
Mattermost deployments.
Fixes https://mattermost.atlassian.net/browse/MM-28636
```release-note
Refactor ClusterInstallation state logic
```
=> Refactor ClusterInstallation state logic

pkg/database/database.go, pkg/database/database_test.go, pkg/mattermost/mattermost.go, pkg/mattermost/mattermost_test.go
This new option allows for setting database read replica endpoints
in the external database secret. The secret key value of
MM_SQLSETTINGS_DATASOURCEREPLICAS will be used to set the correct
environment variable inside the Mattermost deployment. This setting
should be defined as detailed in the Mattermost configuration
documentation.
This change also greatly improves Mattermost deployment unit tests
by checking for more expected environment variables.
Fixes https://mattermost.atlassian.net/browse/MM-28936
```release-note
Add Mattermost database read replica configuration
```
=> Add Mattermost database read replica configuration

pkg/mattermost/mattermost.go, pkg/mattermost/mattermost_test.go
Sets an environment variable to get an idea of the preferred installation type. 
https://mattermost.atlassian.net/jira/software/projects/DOPS/boards/66/backlog?selectedIssue=DOPS-216
```release-note
NONE
```
=> DOPS-216: Add MM_INSTALL_TYPE=kubernetes

pkg/mattermost/mattermost.go, pkg/mattermost/mattermost_test.go
Using the Prometheus operator and the ServiceMonitor it expected the svc exposes the metric port that prometheus can scrape
This PR add this port in the deployment and in the svc to allow prometheus to scrapes 
For MM-cloud we will need a new operator release and deploy that in test to unblock the work that Stelios is doing for the new prometheus
n/a
```release-note
expose metrics port for prometheus operator
```
=> expose metrics port for prometheus operator

apis/mattermost/v1alpha1/clusterinstallation_utils.go
Bump MM version to 5.28.0 because the docker image for the 5.27.0 doesn't have the last mmctl commands and in dev env is not working installation creation
```release-note
Bump default Mattermost version to 5.28.0
```
=> Bump default Mattermost version to 5.28.0

apis/mattermost/v1alpha1/zz_generated.openapi.go, config/rbac/role.yaml, controllers/mattermost/clusterinstallation/bluegreen.go, controllers/mattermost/clusterinstallation/canary.go, controllers/mattermost/clusterinstallation/controller.go, controllers/mattermost/clusterinstallation/create_resources.go, controllers/mattermost/clusterinstallation/mattermost.go, controllers/mattermost/clusterinstallation/mattermost_test.go, docs/mattermost-operator/mattermost-operator.yaml, pkg/mattermost/mattermost.go, pkg/mattermost/mattermost_test.go
To avoid a race condition when two Mattermost pods try to initialize the DB at the same time it should be done before pods startup.
Changes in PR:
- Add a Job that initializes the Mattermost database
- Add init container to Mattermost pod to wait for setup Job to finish
- Adjust RBAC of Mattermost and Operator
```release-note
Add Job that initializes Mattermost database
```
=> Add Job that initializes MM database

apis/mattermost/v1alpha1/clusterinstallation_sizes.go
Looking at our production environment all our installations with 10 or less users average about 3m vCPU and 75Mi per pod so these new requests are still higher than they need to be. Even larger 100 user installations do not use significantly more CPU or memory. We can use these as the starting point for our cloud-specific sizes.
```release-note
Add cloud specific sizes for 10 and 100 users
```
=> Add cloud specific sizes for 10 and 100 users

pkg/database/database.go, pkg/database/database_test.go, pkg/mattermost/mattermost.go, pkg/mattermost/mattermost_test.go
Add the possibility to use init containers that wait for database readiness when using Postgres. Currently, it is only possible with MySQL, which makes pods crash when using Postgres and the DB is not ready.
- Init container type is decided based on the connection string.
- If `DB_CONNECTION_CHECK_URL` is not present in the Secret, the Init container is not added to the pods.
https://mattermost.atlassian.net/browse/MM-30448
See also: https://github.com/mattermost/mattermost-cloud/pull/364
```release-note
Support Init containers waiting for Postgres readiness
```
=> MM-30448 - Support Init containers waiting for Postgres readiness

apis/mattermost/v1alpha1/clusterinstallation_utils.go, controllers/mattermost/clusterinstallation/mattermost.go, controllers/mattermost/clusterinstallation/mattermost_test.go, pkg/mattermost/mattermost_test.go
When updating Cluster Installation with an invalid image and the update job fails it needs to be cleaned up manually.
To remove a need for manual deletion, the Operator will now handle the scenario when the desired image changed.
Changes in the PR:
- Check if the job image matches the desired one
- Restart job if image changed
https://mattermost.atlassian.net/browse/MM-30712
```release-note
Restart update job if image name changed
```
=> MM-30712 - Restart update job if image changed

controllers/mattermost/clusterinstallation/mattermost.go, controllers/mattermost/clusterinstallation/mattermost_test.go, pkg/mattermost/mattermost.go, pkg/mattermost/mattermost_test.go
Due to `mattermost version` command not taking into account custom configuration, we need to disable DB setup job, until the command is implemented or another solution is proposed.
https://mattermost.atlassian.net/browse/MM-31036
```release-note
Disable DB setup job
```
=> Disable DB setup job until we can do it while respecting custom configuration

README.md, scripts/release.sh
Add release script to help in the release cut
now, you need to run `./scripts/release.sh --tag=1.3.4`  and it will:
- bump the version in `version/version.go`
- update the image in `docs/mattermost-operator/mattermost-operator.yaml`
- commit and push to upstream
- tag and push to upstream
Jira:
- https://mattermost.atlassian.net/browse/MM-29303
- https://mattermost.atlassian.net/browse/MM-29601
```release-note
add release script
```
=> [MM-29303] add release script

pkg/components/minio/minio.go, pkg/components/mysql/mysql.go, pkg/database/database.go, pkg/mattermost/database_external.go, pkg/mattermost/database_external_test.go, pkg/mattermost/database_mysql.go, pkg/mattermost/database_mysql_test.go, pkg/mattermost/env_var.go, pkg/mattermost/file_store.go, pkg/mattermost/file_store_test.go, pkg/mattermost/helpers.go, pkg/mattermost/helpers_test.go, pkg/mattermost/mattermost.go, pkg/mattermost/mattermost_v1beta.go, pkg/mattermost/mattermost_v1beta_test.go, pkg/mattermost/util.go
This PR introduces code responsible for generating K8s resources based on the new CRD. The logic was reused in places where it was possible without making too messy code. In other places, the code was copied and modified with the assumption the old code will be removed after the migration is done.
- Introduced `DatabaseConfig` and `FileStoreConfig` interfaces.
- Extracted common logic where possible.
- Performed a couple of refactorings.
https://mattermost.atlassian.net/browse/MM-30827
```release-note
NONE
```
=> Resource generation for Operator beta spec

apis/mattermost/v1alpha1/clusterinstallation_types.go, apis/mattermost/v1alpha1/clusterinstallation_utils.go, apis/mattermost/v1alpha1/zz_generated.openapi.go, config/crd/bases/mattermost.com_clusterinstallations.yaml, controllers/mattermost/clusterinstallation/mattermost.go, pkg/mattermost/mattermost.go
This PR lets the user choose the image pull policy of the mattermost deployment managed by the operator
```release-note
Add ImagePullPolicy to ClusterInstallation spec
```
=> add image pull policy option to spec

test/e2e/main_test.go, test/e2e/mattermost_test.go, test/e2e/utils.go
Switch end to end test to use `Mattermost` resource instead of `ClusterInstallation`.
https://mattermost.atlassian.net/browse/MM-31750
```release-note
NONE
```
=> MM-31750 - Use new Mattermost resource in end to end tests

pkg/mattermost/env_var.go, pkg/mattermost/file_store.go, pkg/mattermost/file_store_test.go, pkg/mattermost/mattermost_v1beta_test.go
`MM_FILESETTINGS_AMAZONS3SSL` will be set to `true` by default when using the external file store and to `false` in case Minio managed by the Minio Operator. User can still override it by explicitly setting `MM_FILESETTINGS_AMAZONS3SSL` in the Mattermost `spec.MattermostEnv` array.
https://mattermost.atlassian.net/browse/MM-29613
```release-note
Breaking change: Set MM_FILESETTINGS_AMAZONS3SSL to true when using external file store
```
=> MM-29613 - Set MM_FILESETTINGS_AMAZONS3SSL to true when using external file store

controllers/mattermost/mattermost/mattermost.go, pkg/mattermost/mattermost_v1beta.go, pkg/mattermost/mattermost_v1beta_test.go
This change contains a small amount of cleanup in the way that
ingress resources are generated.
Fixes https://mattermost.atlassian.net/browse/MM-32560
```release-note
Refactor mattermost ingress resource generation
```
=> Refactor mattermost ingress resource generation

pkg/mattermost/mattermost.go, pkg/mattermost/mattermost_test.go, pkg/mattermost/mattermost_v1beta.go, pkg/mattermost/mattermost_v1beta_test.go
As of Kubernetes 1.18 the default `pathType` in Ingress is set automatically, which causes the Operator to update it every time the resource is reconciled.
https://mattermost.atlassian.net/browse/MM-32818
```release-note
Set Ingress `pathType` to `ImplementationSpecific` for Ingress resource.
```
=> MM-32818 - Set default pathType in Ingress

Makefile, apis/mattermost/v1alpha1/clusterinstallation_utils.go, apis/mattermost/v1alpha1/zz_generated.openapi.go, apis/mattermost/v1beta1/mattermost_utils.go, apis/mattermost/v1beta1/zz_generated.openapi.go
Just catching us up.
Fixes https://mattermost.atlassian.net/browse/MM-35442
```release-note
Bump default Mattermost version to 5.34.2
```
=> Bump default Mattermost version to 5.34.2

config/manager/manager.yaml
This PR adds a Service exposing Mattermost Operator metrics.
Controller Runtime library provides a lot of metrics out of the box but they currently were not accessible for other services like Prometheus. 
Metrics can be accessed under `/metrics` path.
https://mattermost.atlassian.net/browse/MM-35994
```release-note
Expose Mattermost Operator metrics
```
=> MM-35994 - Expose Mattermost Operator metrics

config/rbac/role.yaml
Mattermost Operator RBAC role holds some no longer necessary permissions as well as some duplicated ones.
This PR cleans it up sightly.
https://mattermost.atlassian.net/browse/MM-36993
```release-note
Cleanup Mattermost Operator RBAC role
```
=> MM-36993 - Cleanup Mattermost Operator RBAC role

apis/mattermost/v1beta1/mattermost_types.go, config/crd/bases/installation.mattermost.com_mattermosts.yaml, controllers/mattermost/mattermost/controller.go, controllers/mattermost/mattermost/health_check.go
This change adds an observed generation value to the status object
of the v1beta1 mattermost resource. This value can be used to
determine if the controller has taken action on the latest
generation of the resource or not when the resource state is stable.
This can be used by external clients to ensure that the desired
changes have been properly applied which will avoid possible
race conditions.
Fixes https://mattermost.atlassian.net/browse/MM-37903
```release-note
Set Observed Generation status value
```
=> Set Observed Generation status value

.circleci/config.yml, Makefile, docs/minio-operator/minio-operator.yaml, docs/mysql-operator/mysql-operator.yaml, scripts/kind-config-1.22.yaml, scripts/setup_kind.sh, test/crds/minio_crd.yaml, test/crds/mysql_crd.yaml, test/e2e.sh
This PR update manifests of MinIO and MySQL operators to be compatible with K8s v1.22 where some API versions are removed.
- MySQL CRD manifest is updated from the latest version in the official repository as it seems there was no major version change nor any breaking changes.
- MinIO CRD was adjusted manually as updating to later versions may require additional migration steps.
Additionally, a new temporary job was added `e2e_removed_apis` to run e2e tests on Kind with K8s v1.22.1.
https://mattermost.atlassian.net/browse/MM-38371
```release-note
Update manifests of MinIO and MySQL operators to be compatible with K8s v1.22
```
=> Update manifests of MinIO and MySQL operators to be compatible with K8s v1.22

pkg/mattermost/env_var.go, pkg/mattermost/helpers.go, pkg/mattermost/mattermost.go, pkg/mattermost/mattermost_test.go, pkg/mattermost/mattermost_v1beta.go, pkg/mattermost/mattermost_v1beta_test.go
The issue manifests when Ingress is disabled or a Service LoadBalancer is used.
We should not set `MM_SERVICESETTINGS_SITEURL` env var when ingress host is not provided as this prevents MM from working properly.
Instead, the `SiteURL` will not be set which results in prompting the administrator to set it in System Console.
The `SiteURL` can still be set in the manifest by explicitly providing env var.
https://mattermost.atlassian.net/browse/MM-39871
Fixes #261
```release-note
Do not set SiteURL if ingress host is not provided
```
=> Do not set SiteURL if ingress host is not provided

pkg/mattermost/mattermost_v1beta.go, pkg/mattermost/mattermost_v1beta_test.go
Adds `appProtocol` to the service definition which helps especially with Istio injection so that sidecars know the right protocol.
Fixes #266 
```release-note
Service is now created with appProtocol defined
```
=> Add `appProtocol` to Service Creation

controllers/mattermost/clusterinstallation/controller.go, controllers/mattermost/mattermost/controller.go
Do not log Mattermost CR spec when setting defaults.
```release-note
Do not log Mattermost spec on update
```
=> Do not log Mattermost spec on update

resources/minio.yaml, resources/mm-secrets.yaml, resources/postgres.yaml, test/e2e-external/apply_resource.go, test/e2e-external/external_db_filestore_test.go, test/e2e-external/main_test.go, test/e2e-external/setup_external_resources.go, test/e2e.sh, test/e2e/mattermost_test.go, test/e2e/setup.go, test/e2e/utils.go, test/e2e_local.sh
This PR adds a new e2e test that uses external database and file store configuration instead of Minio and MySQL operators. 
Test deploys Postgres and MinIO locally in the cluster but those are used as an external in CR configuration. 
Tests are more lightweight as they do not require other operators. PR provides a simple framework to easily set up additional tests in isolated namespaces. We can leverage that to implement more e2e tests for more specific configuration options. 
```release-note
Add e2e tests for external DB and file-store configuration
```
=> Add e2e tests for external DB and file-store configuration

controllers/mattermost/clusterinstallation/controller_test.go, controllers/mattermost/mattermost/controller_test.go, pkg/mattermost/healthcheck/health_check.go
Modifies the health check to look specifically at the Mattermost container rather than just container 0.
Fixes https://github.com/mattermost/mattermost-operator/issues/279
```release-note
NONE?
```
=> Image healthcheck with sidecar fix

controllers/mattermost/clusterinstallation/mattermost.go, controllers/mattermost/mattermost/mattermost.go, controllers/mattermost/mattermost/mattermost_test.go, pkg/resources/create_resources.go, pkg/resources/update_job.go
Add `OwnerReference` when updating job
Fixes #215 
```release-note
Add owner reference update-check job
```
=> fix: Add owner reference update-check job

pkg/mattermost/database_mysql.go, pkg/mattermost/mattermost.go, pkg/resources/minio.go
Issue: CLD-2517
Use FQDN to avoid resolve failures when use option ndots<3
Relevant Info: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-aaaa-records-1
https://mattermost.atlassian.net/browse/CLD-2517
```release-note
Use FQDN to avoid resolve failures when use option ndots<3
```
=> Use FQDN to avoid resolve failures when use option ndots<3

controllers/mattermost/mattermost/controller.go, controllers/mattermost/mattermost/mattermost.go, controllers/mattermost/mattermost/mattermost_test.go
- Use `struct` to indicate status of update job check and sleep for 5 seconds before reconciling
Fixes #224 
```release-note
Don't return errors waiting for job update
```
=> Don't return errors waiting for job update

apis/mattermost/v1beta1/mattermost_types.go, controllers/mattermost/mattermost/controller.go, controllers/mattermost/mattermost/controller_test.go, controllers/mattermost/mattermost/health_check.go
An instance is marked as `ready` when at least one pod is updated and all other resources are ready as well.
```release-note
Introduce the 'ready' state to signal instance readiness
```
=> Introduce the 'ready' state to signal instance readiness

controllers/mattermost/mattermost/controller.go, controllers/mattermost/mattermost/controller_test.go, controllers/mattermost/mattermost/health_check.go
Due to changes with `ready` state health check expected at least one pod to be updated which was not the case if replicas are set to 0. This was causing Installation to be stuck in a `reconciling` state.
```release-note
Fix reconciliation of Installation with 0 replicas
```
=> Fix reconciliation of Installation with 0 replicas

controllers/mattermost/mattermost/mattermost.go, controllers/mattermost/mattermost/mattermost_test.go, pkg/mattermost/mattermost_v1beta.go, pkg/resources/create_resources.go
When the service type changes between headless and loadbalancer, the `ClusterIP` field is immutable. This requires the service to be deleted and re-created.
Fixes https://github.com/mattermost/mattermost-operator/issues/244
```release-note
Fixed changing service type between headless service and LoadBalancer
```
=> Fixed changing service type between headless service and LoadBalancer

apis/mattermost/v1beta1/mattermost_types.go, apis/mattermost/v1beta1/mattermost_utils.go, apis/mattermost/v1beta1/zz_generated.deepcopy.go, apis/mattermost/v1beta1/zz_generated.openapi.go, pkg/mattermost/mattermost_v1beta.go, pkg/mattermost/mattermost_v1beta_test.go
Signed-off-by: Micah Nagel <micah.nagel@parsons.com>
Follow on to the discussion in https://github.com/mattermost/mattermost-operator/pull/301#discussion_r961601601
This changes the `podTemplate` in the MM spec to be a pointer (and updates all respective places to ensure nil checks are in place).
```release-note
Update podTemplate to be a pointer
```
=> Update podTemplate to be a pointer

test/e2e-external/apply_resource.go, test/e2e-external/ingress_test.go, test/e2e-external/instance.go, test/e2e/instance.go, test/e2e_local.sh
- Fixed a typo in `tests/e2e_local.sh` causing external tests to not run due to an incorrect path.
- Added a helper mattermost instance manager to the e2e suite to avoid repeating creation an deletion operations in tests.
- Only implemented in this new test, a follow up PR could use it in the other tests as well (but I'm avoiding making this PR very big).
- Added an Ingress test to check that custom values for a Mattermost ingress are kept on instance creation by the operator
- Added an ingress test to check that disabling the ingress after having it enabled correctly disables the ingress on the resource and removes the ingress object from the cluster  
https://github.com/mattermost/mattermost-operator/issues/216
```release-note
NONE
```
```
$ go test ./test/e2e-external --timeout 15m -v …
```
=> [GH-216] Add e2e ingress tests

controllers/mattermost/clusterinstallation/controller_test.go, controllers/mattermost/clusterinstallation/migration.go, controllers/mattermost/clusterinstallation/utils.go, controllers/mattermost/mattermost/controller.go, controllers/mattermost/mattermost/controller_test.go, controllers/mattermost/mattermost/health_check.go, pkg/mattermost/healthcheck/health_check.go
Checking ready replicas in Mattermost Operator is not working as intended as it considers old pods that were not yet terminated as `UpdatedReplicas` if the changes to manifest were something else than the Mattermost version. This causes the Operator to improperly report the `ready` state as it relies on `UpdatedReplicas` in the status.
For this check, we do not need to check all pods one by one but rather we can rely on the status of ReplicaSet which already provides this information.
Old `CheckPodsRollOut` is left out only for the purpose of not changing the migration logic that depends on it. After it is removed it can be cleaned up as well.
Additionally, this fixes a small issue that Mattermost CR might have not been set to a `reconciling` state if the initial update failed and the …
=> Fix replicas status reported in Mattermost CR

go.mod, go.sum, vendor/modules.txt
This PR fixes CVEs reported by `Trivy` scans so that self-hosted customers can get approval to run it in regulated environments. 
`Trivy` version used: `0.32.1`
`Trivy` scan results from the latest image of the operator as published on docker hub:
```trivy image --security-checks vuln --ignore-unfixed --severity HIGH,CRITICAL mattermost/mattermost-operator:v1.18.1
2022-10-11T18:54:18.858-0700    INFO     Need to update DB
2022-10-11T18:54:18.858-0700    INFO     DB Repository: ghcr.io/aquasecurity/trivy-db
2022-10-11T18:54:18.858-0700    INFO     Downloading DB...
34.34 MiB / 34.34 MiB [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 5.54 MiB p/s …
```
=> Update Go deps to mitigate CVEs

apis/mattermost/v1beta1/mattermost_types.go, config/crd/bases/installation.mattermost.com_mattermosts.yaml, controllers/mattermost/mattermost/controller_test.go, controllers/mattermost/mattermost/file_store.go, controllers/mattermost/mattermost/mattermost.go, controllers/mattermost/mattermost/mattermost_test.go, docs/mattermost-operator/mattermost-operator.yaml, pkg/mattermost/env_var.go, pkg/mattermost/file_store.go, pkg/mattermost/file_store_test.go
Makes using a secret for S3 optional. Instead, gives an option to UseServiceAccount instead.
This feature is quite important to ensure security standards.
Fixes #315 
```release-note
Makes using a secret for S3 calls optional, gives an option to UseServiceAccount with IAM role instead.
```
=> feat(filestore): use service account for s3 api calls

.github/workflows/ci.yml
Use custom GOPATH in github actions
Trying to workaround https://github.com/kubernetes/gengo/issues/147
```release-note
none
```
=> Use custom GOPATH in github actions

test/e2e.sh
This resolves the `detected dubious ownership in repository` issue that popped up with newer golang images. `v1.19.5` and above currently have this issue. We will fix the underlying issue when we migrate to github actions.
```release-note
Hardcode e2e golang image to v1.19.4
```
=> Hardcode e2e golang image to v1.19.4

controllers/mattermost/mattermost/controller.go, controllers/mattermost/mattermost/controller_test.go
Installations that are in the `ready` state are nearly done reconciling, but should be treated the same until they are stable. This change corrects an issue where the limiter logic for concurrent reconciliations treated the `ready` installations as if they weren't reconciling yet. This can lead to them not properly being prioritized to check when they are stable when reconciling many installations all at once.
Fixes https://mattermost.atlassian.net/browse/MM-50752
```release-note
Include `ready` installations in reconcile limit check
```
=> Include `ready` installations in reconcile limit check

.github/workflows/cd.yml, .github/workflows/ci.yml
- Fix Docker login on cd workflow
- Use proper permissions for security upload results
https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#example-workflow-for-sarif-files-generated-outside-of-a-repository
```release-note
```
=> fix(ci): Hotfix permissions for trivy push and docker login

pkg/resources/update_job.go
This fixes the removal of the store initialialization for the version command of the mattermost server under
https://github.com/mattermost/mattermost-server/pull/19364
None
```release-note
fix: use `mattermost db migration` for database migrations instead of `mattermost version`
```
=> fix: run db migration instead of version command

.github/workflows/cd.yml, .github/workflows/ci.yml
According to Github documentation[^1], using `v1.**` triggers any `v1.XXX` tag, which means that the expression is not really a regex. I changed the push triggers to `v**` to ensure that it trigger on any new version tag.
None
```release-note
none
```
[^1]: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs
=> fix: workflow push tag triggers

.github/workflows/cd.yml, .github/workflows/ci.yml, Dockerfile, go.mod, test/e2e.sh
Fixes https://mattermost.atlassian.net/browse/CLD-6261
```release-note
Bump Go to version 1.21
```
=> Bump Go to version 1.21

apis/mattermost/v1alpha1/clusterinstallation_sizes.go
This size had the same values as 10000users. This change bumps the resource requests and limits up to better support more users.
Fixes https://mattermost.atlassian.net/browse/CLD-6216
```release-note
Fix installation size 25000users
```
=> Fix installation size 25000users

Dockerfile, Makefile
This PR fix arm64 build.
*__Note:__ cf. https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope.*
Fixes https://github.com/mattermost/mattermost-operator/issues/359.
```release-note
support arm64 builds/binaries
```
=> feat: allow customizable target arch/platform on make build command

.github/workflows/cd.yml, .github/workflows/ci.yml
This change does the following:
- Bumps `actions/checkout` to `v3.6.0`
- Uses `go.mod` for Go versioning instead of hardcoding value
- Removes extra `cd` workflow checks
Fixes https://mattermost.atlassian.net/browse/CLD-6451
```release-note
None
```
=> Cleanup CI/CD

apis/mattermost/v1alpha1/clusterinstallation_utils.go, apis/mattermost/v1beta1/mattermost_utils.go, test/constants.go
The default has been updated to v9.2.3
Fixes https://mattermost.atlassian.net/browse/CLD-6819
```release-note
Bump default Mattermost server version
```
=> Bump default Mattermost server version

apis/mattermost/v1alpha1/clusterinstallation_utils.go, test/constants.go, version/version.go
This change also updates the default Mattermost version to v9.5.1.
```release-note
Bump Operator and default Mattermost versions
```
=> Bump Operator version number

pkg/mattermost/mattermost.go, pkg/mattermost/mattermost_test.go, pkg/mattermost/mattermost_v1beta.go, pkg/mattermost/mattermost_v1beta_test.go
This change replaces the deprecated annotation
`service.alpha.kubernetes.io/tolerate-unready-endpoints` with the PublishNotReadyAddresses service setting when generating services.
Fixes https://mattermost.atlassian.net/browse/CLD-7415 and https://github.com/mattermost/mattermost-operator/issues/369
```release-note
Use PublishNotReadyAddresses for services
```
=> Use PublishNotReadyAddresses for services

resources/postgres.yaml, test/e2e-external/ingress_test.go, test/e2e-external/size_test.go, test/e2e-external/upgrade_test.go, test/e2e/mattermost_test.go, test/e2e/utils.go
This change does the following:
- Converts individual external E2E tests to subtests. This now matches the standard E2E test flow and provides better test logging output.
- Split Mattermost version upgrade test out from base test.
- Improve reconciliation logging with more status output.
- Improve reconciliation check with ObservedGeneration validation.
- Update external E2E postgres container image to version 14.
Fixes https://mattermost.atlassian.net/browse/CLD-7478
```release-note
Improve external E2E test logic
```
=> Improve external E2E test logic

pkg/mattermost/mattermost_v1beta.go, pkg/mattermost/mattermost_v1beta_test.go
There was an edge case where extra service annotations were not applied to the service created by the operator. This change ensures that extra annotations are always applied to all service types.
Fixes https://mattermost.atlassian.net/browse/CLD-7557
```release-note
Apply custom service annotations in all cases
```
=> Apply custom service annotations in all cases

apis/mattermost/v1alpha1/clusterinstallation_utils.go, apis/mattermost/v1beta1/mattermost_utils.go, test/constants.go, version/version.go
This also updates the default Mattermost version to 9.7.3.
Fixes https://mattermost.atlassian.net/browse/CLD-7571
```release-note
None
```
=> Bump operator version to v1.22

pkg/mattermost/helpers.go
Currently you can set some custom values for liveness probes but you can't set the timeout. I ran into an issue and needed to set it.
=> allow setting a custom liveness probe timeout

apis/mattermost/v1alpha1/clusterinstallation_utils.go, apis/mattermost/v1beta1/mattermost_utils.go, docs/mattermost-operator/mattermost-operator.yaml, test/constants.go, version/version.go
Updates the operator to v1.23.0 and the default Mattermost version to v10.5.1.
```release-note
Bump Operator and Mattermost versions
```
=> Bump Operator and Mattermost versions

pkg/mattermost/mattermost_v1beta.go, pkg/mattermost/mattermost_v1beta_test.go
This env var setting should remain as the default `true` value for the main Mattermost deployment.
Fixes https://mattermost.atlassian.net/browse/CLD-8876
```release-note
Remove job scheduling env when using dedicated job server
```
=> Remove job scheduling env when using dedicated job server

pkg/mattermost/helpers.go
Adding custom readiness probe timeout
```release-note
None
```
=> Add custom redinessprobe timeout

.github/workflows/ci.yml
Skip build job for dependabot PRs
- Updated the build job condition in CI workflow to exclude dependabot[bot] actor
- Prevents unnecessary Docker builds and security scans on automated dependency updates
- Build job now only runs when the actor is not dependabot and it's either a PR or master branch push
This optimization reduces CI resource usage and build times for dependabot PRs while maintaining full CI coverage for human-authored changes.
https://mattermost.atlassian.net/browse/CLD-9306
```release-note
NONE
```
=> Update CI workflow configuration

.github/workflows/cd.yml, .github/workflows/ci.yml, Dockerfile.fips, Makefile, scripts/build_image.sh
This change introduces separate build targets in the Makefile and parallel-running GitHub Actions to produce FIPS-compliant Mattermost Operator releases. The changes do not affect the current release pipelines, explicitly including `continue-on-error` and the ability to disable/enable them through an environment variable.
https://mattermost.atlassian.net/browse/MM-64292
```release-note
Introduction of FIPS-compliant Operator Releases
```
=> Introduction of FIPS Release Pipeline
