mattermost/mattermost-operator

- .circleci/config.yml
- Makefile
> add coveralls

- .dockerignore
- .editorconfig
- test/e2e.sh
when creating the kind cluster with --wait flag the command finish when the cluster is ready, so we dont need to check if the cluster is ready to use.
> remove check because kind already checks with --wait flag

- .circleci/config.yml
Add the ability to push the images when we have new things on master and when we tag a release
> push docker images on master and tagged releases

- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
Define Image and Version for the Mattermost
Jira: https://mattermost.atlassian.net/browse/MM-14983
> Define image and version

- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- pkg/components/minio/minio.go
- pkg/components/mysql/mysql.go
- pkg/controller/clusterinstallation/controller.go
- pkg/controller/clusterinstallation/create_resources.go
- pkg/controller/clusterinstallation/mattermost.go
- pkg/controller/clusterinstallation/minio.go
- pkg/controller/clusterinstallation/mysql.go
- pkg/controller/clusterinstallation/postgresql.go
- pkg/controller/clusterinstallation/utils.go
This change offers the following improvements to the operator:
- Controller code refactoring and cleanup
- Minio image lock-in
- Fix to stop Minio updates on every reconciliation loop
- Set mysql member count to 1 as a temporary fix for the RO
database bug.
Fixes https://mattermost.atlassian.net/browse/MM-15640
Fixes https://mattermost.atlassian.net/browse/MM-15649
Temporary workaround for https://mattermost.atlassian.net/browse/MM-15585
> [MM-15640| MM-15649] Various operator improvements

- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- test/e2e.sh
- test/e2e/mattermost_test.go
- test/e2e/utils.go
- default mattermost-operator to use mattermost version 5.11.0
- add upgrade test
> Add upgrade test

- .circleci/config.yml
- pkg/controller/clusterinstallation/controller_test.go
- test/e2e/mattermost_test.go
Adding scale up/down e2e tests
> add scale up/down tests

- deploy/crds/mattermost_v1alpha1_clusterinstallation_crd.yaml
- pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- pkg/components/mysql/mysql.go
- test/e2e.sh
- test/e2e/mattermost_test.go
- test/local-path-provisioner.yaml
this PR adds a persistent volume to mysql
> [MM-15598] add persistent volume to mysql

- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
Trying this to see if it resolves our HTTPS ELB issue.
> Reorder Mattermost Service Ports

- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- wait for minio be up and running
- added other smalls improvements
> Wait for minio start as well

- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- Adds the site url as env variable
> add site url env var

- deploy/crds/mattermost_v1alpha1_clusterinstallation_crd.yaml
- deploy/operator.yaml
- docs/mattermost-operator/mattermost-operator.yaml
- pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- pkg/apis/mattermost/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go
- similar to what we did for the service, now for the ingress
> adding ingress annotations

- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
This worked better locally at least.
Docs: https://docs.min.io/docs/minio-monitoring-guide.html
> Change Minio wait check command

- test/e2e.sh
- test/kind-config.yaml
- test/local-path-provisioner.yaml
- update local path provisioner
- add more images to kind to make it available during the tests
- set go test timeout to 30m
note: the Kind update i will need some time to figure out what is happening
> update local path provisioner

- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
This PR adds the ability to create the initial MinIO bucket that will store the data from the users
> [MM-16529] create minio bucket

- deploy/crds/mattermost_v1alpha1_clusterinstallation_crd.yaml
- docs/mattermost-operator/mattermost-operator.yaml
- pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go
- pkg/controller/clusterinstallation/controller.go
- pkg/controller/clusterinstallation/mattermost.go
- pkg/controller/clusterinstallation/utils.go
- test/e2e.sh
- Add a mattermost license using the secret.
> add mattermost license

- Makefile
- docs/mattermost-operator/mattermost-operator.yaml
https://mattermost.atlassian.net/browse/MM-16257
> MM-16257 Add sed to make yaml command to replace docker tag

- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- pkg/controller/clusterinstallation/mattermost.go
- pkg/controller/clusterinstallation/mysql.go
This removes the init container to create the database and leave to the mysql operator to do that for us
> remove the init container to create the db and use from the operator

- docs/examples/full.yaml
- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- test/e2e.sh
- test/e2e/mattermost_test.go
this PR update the default mattermost image to use the latest releases in this case: 5.12.4
> update mattermost image version

- deploy/role.yaml
- docs/minio-operator/minio-operator.yaml
- test/e2e.sh
Now MinIO tagged their operator lets use that :)
> use tagged minio operator

- pkg/apis/mattermost/v1alpha1/clusterinstallation_sizes.go
- pkg/apis/mattermost/v1alpha1/clusterinstallation_test.go
This change introduces resource calculations for cluster
installation sizes. This allows for better scheduling of the
installations on k8s clusters.
https://mattermost.atlassian.net/browse/MM-17521
> [MM-17521] Add cluster size resource calculations

- deploy/crds/mattermost_v1alpha1_clusterinstallation_crd.yaml
- docs/mattermost-operator/mattermost-operator.yaml
- pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- pkg/components/minio/minio.go
- pkg/controller/clusterinstallation/minio.go
Resolves [#11817](https://github.com/mattermost/mattermost-server/issues/11817)
> Added Custom Secret support for Minio

- deploy/crds/mattermost_v1alpha1_clusterinstallation_crd.yaml
- docs/mattermost-operator/mattermost-operator.yaml
- pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- pkg/controller/clusterinstallation/mattermost.go
- pkg/controller/clusterinstallation/minio.go
https://mattermost.atlassian.net/browse/MM-17587
> MM-17587 Allow using external MinIO/S3 instances

- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
Ticket -> https://mattermost.atlassian.net/browse/MM-19178
> MM-19178 Adding logic for support of multiple file size types

- .github/workflows/clean_docker.yml
perform some cleanup when a PR is merged removing the docker image created for the PR
added a `|| true`  in the docker delete to not fail the command
> delete docker images when PR is merged

- .circleci/config.yml
push the operator image using the short SHA
> push docker image for PR/branch using the short sha

- deploy/crds/mattermost_v1alpha1_clusterinstallation_crd.yaml
- docs/mattermost-operator/mattermost-operator.yaml
- pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
- pkg/controller/clusterinstallation/bluegreen.go
- pkg/controller/clusterinstallation/controller_test.go
- pkg/controller/clusterinstallation/mattermost.go
- pkg/controller/clusterinstallation/utils.go
https://mattermost.atlassian.net/browse/MM-19204
> MM-19204 Perform clean-up when switching to/from blue green

- .github/workflows/cleandocker.yml
> make it a bit simpler

- deploy/crds/mattermost_v1alpha1_clusterinstallation_crd.yaml
- pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- pkg/components/minio/minio.go
- pkg/components/mysql/mysql.go
- pkg/controller/clusterinstallation/controller.go
- pkg/controller/clusterinstallation/controller_test.go
- pkg/controller/clusterinstallation/mattermost.go
- pkg/controller/clusterinstallation/mattermost_test.go
- pkg/controller/clusterinstallation/mysql.go
- pkg/controller/mattermostrestoredb/mysql.go
Changes:
- Document different configurations of the database secret.
- Handle different database configurations when reconciling.
- General code and logging cleanup.
> Database code improvements

- cmd/manager/main.go
- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- test/e2e/mattermost_test.go
Introduce proper values for deployment rolling-update parameters
1. MaxUnavailable
2. MaxSurge
> Clarify rolling-update process (#13094)

- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- pkg/controller/clusterinstallation/mattermost.go
It should be done explicitly. Clarify update deployment function
> Change assumption that 0-index container is "mattermost"

- .github/workflows/cleandocker.yml
Reverts mattermost/mattermost-operator#101
adding back :D
> Revert "Remove Github workflows"

- docs/examples/full.yaml
- pkg/apis/mattermost/v1alpha1/clusterinstallation_test.go
- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- pkg/controller/clusterinstallation/controller_test.go
- pkg/controller/clusterinstallation/mattermost_test.go
- test/e2e/mattermost_test.go
Update operator to use MM 5.18.0
> update operator to use 5.18.0

- .circleci/config.yml
giving more cpu and memory to run the tests
large machine have:
- 4 vCpus
- 15GB Memory
- Fixes https://mattermost.atlassian.net/browse/MM-21759
> increase the machine type to large

- deploy/crds/mattermost.com_clusterinstallations_crd.yaml
- go.mod
- go.sum
- pkg/apis/mattermost/v1alpha1/clusterinstallation_test.go
- pkg/apis/mattermost/v1alpha1/clusterinstallation_types.go
- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- pkg/apis/mattermost/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/mattermost/v1alpha1/zz_generated.openapi.go
- vendor/golang.org/x/tools/go/analysis/doc.go
- vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
- vendor/golang.org/x/tools/go/packages/golist.go
- vendor/golang.org/x/tools/go/packages/golist_overlay.go
- vendor/golang.org/x/tools/internal/fastwalk/fastwalk.go
- vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
- vendor/golang.org/x/tools/internal/fastwalk/fastwalk_unix.go
- vendor/golang.org/x/tools/internal/gopathwalk/walk.go
- vendor/golang.org/x/tools/internal/imports/fix.go
- vendor/golang.org/x/tools/internal/imports/mod_cache.go
- vendor/modules.txt
Add option to custom define the liveness and readiness probes
> add custom liveness and readiness probes in the spec for clusterinstallation

- .circleci/config.yml
- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
- test/e2e.sh
- test/e2e/mattermost_test.go
Since we use immutable tags we dont need to pull the images always, also this will accelerate the deployment when using the cloud offer
> pull mattermost images if not present

- version/version.go
Just to match our latest release tag.
> Bump internal version variable

- .github/PULL_REQUEST_TEMPLATE.md
Add PR template
NA
```release-note
NONE
```
> github/template: add PR template

- go.mod
- go.sum
- hack/tools.go
- vendor/modules.txt
Looks like now we need to explicitly declare the dependencies
```release-note
NONE
```
> fix broken master

- version/version.go
prepare for the new release
we will release a version 1.8.0
```release-note
NONE
```
> prepare for the new release

- pkg/apis/mattermost/v1alpha1/clusterinstallation_utils.go
```release-note
Bump default Mattermost version to 5.27.0
```
> Bump default Mattermost version to 5.27.0

- config/crd/bases/mattermost.com_clusterinstallations.yaml
- config/crd/bases/mattermost.com_mattermostrestoredbs.yaml
- docs/mattermost-operator/mattermost-operator.yaml
Regenerate manifest files.
```release-note
NONE
```
> Regenerate manifests

- version/version.go
Pushing the version to 1.11.0
-->
```release-note
None
```
> Pushing the version to 1.11.0

- apis/mattermost/v1alpha1/clusterinstallation_sizes.go
Decrease the requests of small cloud cluster installations.
Decrease the requests of small cloud cluster installations.
https://mattermost.atlassian.net/browse/MM-31880
```release-note
NONE
```
> MM-31880 - Decrease the requests of small cloud cluster installations

- README.md
Add the correct script on README.
```release-note
NONE
```
> README fix on release process

- README.md
- docs/migration.md
Add documentation on how to migrate to `Mattermost` Custom Resource.
https://mattermost.atlassian.net/browse/MM-31748
```release-note
Add documentation on how to migrate to Mattermost CR
```
> MM-31748 - Add documentation on how to migrate to Mattermost CR

- docs/examples/mattermost_full.yaml
- docs/examples/mattermost_mysql_minio_operators_small.yaml
- docs/examples/mattermost_simple_anywhere.yaml
- docs/examples/mattermost_simple_aws_azure.yaml
Add examples of new resource, to document all fields and reference them in documentation.
Part of https://mattermost.atlassian.net/browse/MM-31749
```release-note
Add examples of new Mattermost Custom Resource
```
> Add examples for new Mattermost CR

- .github/ISSUE_TEMPLATE.md
Add GitHub issue tamplate.
https://mattermost.atlassian.net/browse/MM-32666
```release-note
NONE
```
> MM-32666 - Add issue template for Mattermost Operator repository

- README.md
- docs/mattermost-operator/mattermost-operator.yaml
Prepare manifests for new Operator release.
```release-note
Prepare Operator manifest for new release.
```
> Prepare Operator manifest for new release

- README.md
Mention in README how to run Operator on the local machine against K8s cluster.
https://mattermost.atlassian.net/browse/MM-32705
```release-note
NONE
```
> MM-32705 - Document running Operator locally for development

- apis/mattermost/v1alpha1/clusterinstallation_utils.go
- apis/mattermost/v1beta1/mattermost_utils.go
```release-note
Bump default mattermost version to 5.37.1
```
> Bump default mattermost version to 5.37.1

- docs/mattermost-operator/mattermost-operator.yaml
```release-note
Prepare Operator manifests for new release
```
> Prepare Operator manifests for new release

- Makefile
- controllers/mattermost/mattermost/controller.go
- controllers/mattermost/mattermost/controller_test.go
- controllers/mattermost/mattermost/utils.go
This PR changes logic that updates the state to update the whole status if there are any changes. 
```release-note
Always update Mattermost status if there are any differences
```
> Always update Mattermost status if there are any differences

- docs/examples/mattermost_full.yaml
- docs/examples/mattermost_mysql_minio_operators_small.yaml
- docs/examples/mattermost_simple_anywhere.yaml
- docs/examples/mattermost_simple_aws_azure.yaml
Update examples to use new Ingress configuration.
https://mattermost.atlassian.net/browse/MM-39515
```release-note
Update examples to use new configuration
```
> Update examples to use new configuration

- docs/mattermost-operator/mattermost-operator.yaml
This PR updates the Operator installation manifest before cutting the new release.
https://mattermost.atlassian.net/browse/MM-40745
```release-note
NONE
```
> Prepare manifest for new release

- docs/mattermost-operator/mattermost-operator.yaml
Prepare operator manifests for release.
```release-note
NONE
```
> Prepare manifests for release

- .circleci/config.yml
- scripts/go_install.sh
Use `go install` instead of `go get` for installing tools.
```release-note
Use `go install` instead of `go get` for installing tools.
```
> Fix go_install.sh script

- pkg/resources/update_job.go
We are injecting cloudsql-proxy sidecar via a `resourcePatch`. However the operator is changing the command in that container as well to `mattermost version`. This patch will avoid that by matching the container name.
```release-note
Fix update-check overriding commands in all containers.
```
> Avoid rewriting command for injected sidecars

- test/e2e-external/external_db_filestore_test.go
- test/e2e/utils.go
Added e2e test to ensure if version upgrading works or not.
Fixes https://github.com/mattermost/mattermost-operator/issues/306
```release-note
Added e2e test to ensure if version upgrading works or not.
````
> e2e test for version upgrade

- apis/mattermost/v1beta1/mattermost_test.go
- test/constants.go
Update MattermostVersion in test.
```
LatestStableMattermostVersion = "7.3.0"
PreviousStableMattermostVersion = "7.2.0"
```
```release-note
Update MattermostVersion in test.
```
> update MattermostVersion in test

- test/e2e-external/size_test.go
- test/e2e-external/utils.go
Added e2e test to see if size and resource updates work.
Fixes https://github.com/mattermost/mattermost-operator/issues/307
```release-note
Added e2e test to see if size and resource updates work.
```
> e2e test for size & resource update

- apis/mattermost/v1alpha1/clusterinstallation_utils.go
- apis/mattermost/v1beta1/mattermost_utils.go
- test/constants.go
Just getting things up to date.
```release-note
None
```
> Bump default Mattermost version

- apis/mattermost/v1alpha1/clusterinstallation_sizes.go
These values were changed to be more similar to the cloud sizes.
```release-note
Update dev size resource values
```
> Update dev size resource values

- README.md
Added a `GOPATH` notice for module contributors when making changes to manifest files.
Refs: https://github.com/mattermost/mattermost-operator/pull/337
None
```release-note
docs: added GOPATH notice
```
> docs: added GOPATH notice

- .github/workflows/cd.yml
Addition to #351 for the continuous delivery workflow.
None
```release-note
none
```
> cd: also enable on rc branches

- .github/dependabot.yml
Add dependabot in mattermost-operator
https://mattermost.atlassian.net/browse/CLD-8887
```release-note
NONE
```
> Add dependabot in mattermost-operator
